タスク管理アプリの課題を実行中なのですが、
InputViewContorollerでタスクを文字を書いた後にBackで戻っているのですが、

ViewWillDisapperarメソッドの中身はしっかり記述しているのですが、Backで戻っても表示されません



InputContorollerのViewWillAppearも正しく記述しているのですが、

とりあえずRealmデーターベースに入力したデータが保存されているのか確認すればどこで止まってるのかわかるのですが、

Webアプリケーションではuse Database 、show tables などでやってましたが、


Realmではどうやるのでしょう？